Notebook pre-requisites:

In [156]:
!pip install "camelot-py[cv]"
!pip install spacy

Requirement already satisfied: camelot-py[cv] in ./.venv/lib/python3.10/site-packages (1.0.9)
WARNING: camelot-py 1.0.9 does not provide the extra 'cv'
Requirement already satisfied: click>=8.0.1 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (8.3.0)
Requirement already satisfied: chardet>=5.1.0 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (5.2.0)
Requirement already satisfied: numpy>=1.24.4 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (2.2.6)
Requirement already satisfied: openpyxl>=3.1.0 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (3.1.5)
Requirement already satisfied: pdfminer-six>=20240706 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (20250506)
Requirement already satisfied: pypdf<4.0,>=3.17 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (3.17.4)
Requirement already satisfied: pandas>=2.2.2 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (2.3.3)
Requirement already satisfied: tabulate>=0.9.0 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (0.9.0)
Requirement already satisfied: typing-extensions>=4.12.2 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (4.15.0)
Requirement already satisfied: opencv-python-headless>=4.7.0.68 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (4.12.0.88)
Requirement already satisfied: pypdfium2>=4 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (4.30.0)
Requirement already satisfied: pillow>=10.4.0 in ./.venv/lib/python3.10/site-packages (from camelot-py[cv]) (12.0.0)
Requirement already satisfied: et-xmlfile in ./.venv/lib/python3.10/site-packages (from openpyxl>=3.1.0->camelot-py[cv]) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.10/site-packages (from pandas>=2.2.2->camelot-py[cv]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.10/site-packages (from pandas>=2.2.2->camelot-py[cv]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.10/site-packages (from pandas>=2.2.2->camelot-py[cv]) (2025.2)
Requirement already satisfied: charset-normalizer>=2.0.0 in ./.venv/lib/python3.10/site-packages (from pdfminer-six>=20240706->camelot-py[cv]) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in ./.venv/lib/python3.10/site-packages (from pdfminer-six>=20240706->camelot-py[cv]) (46.0.3)
Requirement already satisfied: cffi>=2.0.0 in ./.venv/lib/python3.10/site-packages (from cryptography>=36.0.0->pdfminer-six>=20240706->camelot-py[cv]) (2.0.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.10/site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer-six>=20240706->camelot-py[cv]) (2.23)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.2->camelot-py[cv]) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: spacy in ./.venv/lib/python3.10/site-packages (3.8.7)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./.venv/lib/python3.10/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./.venv/lib/python3.10/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./.venv/lib/python3.10/site-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./.venv/lib/python3.10/site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./.venv/lib/python3.10/site-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in ./.venv/lib/python3.10/site-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./.venv/lib/python3.10/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in ./.venv/lib/python3.10/site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./.venv/lib/python3.10/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in ./.venv/lib/python3.10/site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in ./.venv/lib/python3.10/site-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./.venv/lib/python3.10/site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in ./.venv/lib/python3.10/site-packages (from spacy) (2.2.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./.venv/lib/python3.10/site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in ./.venv/lib/python3.10/site-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.10/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in ./.venv/lib/python3.10/site-packages (from spacy) (58.1.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.10/site-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in ./.venv/lib/python3.10/site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in ./.venv/lib/python3.10/site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in ./.venv/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in ./.venv/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in ./.venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in ./.venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in ./.venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in ./.venv/lib/python3.10/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in ./.venv/lib/python3.10/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.4.1)
Requirement already satisfied: wrapt in ./.venv/lib/python3.10/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (2.0.0)
Requirement already satisfied: marisa-trie>=1.1.0 in ./.venv/lib/python3.10/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.10/site-packages (from jinja2->spacy) (3.0.3)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [157]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 25.2 MB/s  0:00:00 eta 0:00:01

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [158]:
!pip install PyMuPDF
!pip install pdfplumber

Requirement already satisfied: PyMuPDF in ./.venv/lib/python3.10/site-packages (1.26.5)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pdfplumber in ./.venv/lib/python3.10/site-packages (0.11.7)
Requirement already satisfied: pdfminer.six==20250506 in ./.venv/lib/python3.10/site-packages (from pdfplumber) (20250506)
Requirement already satisfied: Pillow>=9.1 in ./.venv/lib/python3.10/site-packages (from pdfplumber) (12.0.0)
Requirement already satisfied: pypdfium2>=4.18.0 in ./.venv/lib/python3.10/site-packages (from pdfplumber) (4.30.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in ./.venv/lib/python3.10/site-packages (from pdfminer.six==20250506->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in ./.venv/lib/python3.10/site-packages (from pdfminer.six==20250506->pdfplumber) (46.0.3)
Requirement already satisfied: cffi>=2.0.0 in ./.venv/lib/python3.10/site-packages (from cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (2.0.0)
Requirement already satisfied: typing-extensions>=4.13.2 in ./.venv/lib/python3.10/site-packages (from cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (4.15.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.10/site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (2.23)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

## 1. PDF Ingestion & Parsing
- Extract text with page/section anchors (page number, heading hierarchy).
- Preserve structure: titles, subsections, lists, tables, figures’ captions.
- For tables: parse into machine-readable frames (CSV/JSON) when possible.
- Deliverables: raw_text.jsonl (chunks with metadata), tables/*.csv.

In [159]:
import fitz
import json
import re
from pathlib import Path
import shutil
import camelot
import pdfplumber
import pandas as pd

# =============== TOC EXTRACTION ===============
def extract_contents_section(doc):
    toc_lines = []
    toc_started = False
    current_title = ""
    suppressing = False  # True when we've seen THL but not yet seen FOOD

    toc_header_re = re.compile(r"\b(Contents|Table of Contents)\b", re.IGNORECASE)
    toc_entry_re = re.compile(r"\.{3,}\s*(\d+)$")  # dots then page number at EOL
    thl_re = re.compile(r"THL", re.IGNORECASE)
    food_re = re.compile(r"FOOD", re.IGNORECASE)

    for page in doc:
        lines = page.get_text().splitlines()
        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue
            if not toc_started and toc_header_re.search(stripped):
                toc_started = True
                continue
            if not toc_started:
                continue

            # suppression logic
            if suppressing:
                m_food = food_re.search(stripped)
                if m_food:
                    stripped = stripped[m_food.end():].strip()
                    suppressing = False
                    if not stripped:
                        continue
                else:
                    continue

            m_thl = thl_re.search(stripped)
            if m_thl:
                m_food = food_re.search(stripped, m_thl.end())
                if m_food:
                    stripped = stripped[m_food.end():].strip()
                    if not stripped:
                        continue
                else:
                    stripped = stripped[:m_thl.start()].strip()
                    suppressing = True
                    if not stripped:
                        continue

            match = toc_entry_re.search(stripped)
            if match:
                full_title = (current_title + " " + stripped).strip() if current_title else stripped
                toc_lines.append(full_title)
                current_title = ""
            else:
                if current_title:
                    current_title += " " + stripped
                else:
                    current_title = stripped

        last_few = lines[-5:]
        if toc_started and all(not toc_entry_re.search(l.strip()) for l in last_few):
            break

    if current_title:
        if suppressing:
            last_thl = re.search(r"THL", current_title, re.IGNORECASE)
            cleaned_title = current_title[:last_thl.start()].strip() if last_thl else ""
        else:
            cleaned_title = current_title.strip()
        if cleaned_title:
            toc_lines.append(cleaned_title)

    return "\n".join(toc_lines)

# =============== PARSE CONTENTS TO DATAFRAME ===============
def parse_contents_to_df(contents_text):
    lines = [l.strip() for l in contents_text.split("\n") if re.search(r"\d+\s*$", l)]
    rows = []
    for line in lines:
        match = re.match(r"(.+?)\s+(\d+)$", line)
        if match:
            title, page = match.groups()
            title = re.sub(r"\.{2,}", "", title).strip()
            rows.append([title, int(page)])
    df = pd.DataFrame(rows, columns=["title", "page"])
    df = merge_split_rows(df)
    return df

def merge_split_rows(df):
    return df

def normalize_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^\w\s]', '', text)
    return text.strip().lower()

# =============== TABLE EXTRACTION USING CAMELT/PLUMBER ===============
def extract_tables(pdf_path, output_dir):
    output_dir = Path(output_dir)
    tables_dir = output_dir / "tables"
    if tables_dir.exists():
        shutil.rmtree(tables_dir)
    tables_dir.mkdir(exist_ok=True)

    all_tables = []
    doc = fitz.open(pdf_path)

    for page_num in range(len(doc)):
        page_str = str(page_num + 1)
        page_tables = []

        # Camelot STREAM
        try:
            tables_stream = camelot.read_pdf(pdf_path, pages=page_str, flavor='stream', edge_tol=50, row_tol=10, strip_text='\n')
            page_tables += [t.df for t in tables_stream if not t.df.empty]
        except Exception:
            pass

        # Camelot LATTICE
        if not page_tables:
            try:
                tables_lattice = camelot.read_pdf(pdf_path, pages=page_str, flavor='lattice', line_scale=40, shift_text=['l','t'])
                page_tables += [t.df for t in tables_lattice if not t.df.empty]
            except Exception:
                pass

        # pdfplumber fallback
        if not page_tables:
            with pdfplumber.open(pdf_path) as pdf:
                page = pdf.pages[page_num]
                plumber_tables = page.extract_tables()
                for pt in plumber_tables:
                    df = pd.DataFrame(pt)
                    page_tables.append(df)

        # Save tables
        for i, df in enumerate(page_tables):
            df = df.fillna("").astype(str).apply(lambda col: col.map(lambda x: re.sub(r"\n", " ", x).strip()))
            df = merge_split_rows(df)
            table_file = tables_dir / f"table_page{page_num+1}_{i+1}.csv"
            df.to_csv(table_file, index=False)
            all_tables.append({
                "table_number": i + 1,
                "page": page_num + 1,
                "file": str(table_file),
                "rows": df.shape[0],
                "columns": df.shape[1]
            })

    print(f"✓ Extracted {len(all_tables)} tables total to '{tables_dir}'")
    return all_tables

# =============== MAIN EXTRACTION FUNCTION ===============
def extract_pdf_with_structure(pdf_path, output_dir="data"):
    output_dir = Path(output_dir)
    output_dir.mkdir(exist_ok=True)

    doc = fitz.open(pdf_path)
    chunks = []

    # --- Extract TOC and parse ---
    contents_text = extract_contents_section(doc)
    toc_df = parse_contents_to_df(contents_text)
    toc_df = toc_df.sort_values(by="page").reset_index(drop=True)

    toc_index = 0
    current_section = ""

    for page_num in range(len(doc)):
        page = doc[page_num]
        lines = page.get_text().splitlines()

        new_sections = []
        while toc_index < len(toc_df) and toc_df.loc[toc_index, "page"] <= page_num + 1:
            new_sections.append(toc_df.loc[toc_index, "title"])
            toc_index += 1

        pending_sections = new_sections.copy()
        buffer = []
        line_idx = 0

        while line_idx < len(lines):
            matched_section = None
            matched_lines_count = 0
            for section_title in pending_sections:
                for lookahead in range(1, min(5, len(lines) - line_idx + 1)):
                    candidate_text = " ".join(lines[line_idx:line_idx+lookahead])
                    if normalize_text(candidate_text).startswith(normalize_text(section_title)):
                        matched_section = section_title
                        matched_lines_count = lookahead
                        break
                if matched_section:
                    break

            if matched_section:
                if current_section and buffer:
                    text_chunk = " ".join(buffer).strip()
                    if text_chunk:
                        chunks.append({"page": page_num+1, "section": current_section, "text": text_chunk})
                current_section = matched_section
                buffer = []
                pending_sections.remove(matched_section)
                line_idx += matched_lines_count
                continue
            else:
                if current_section:
                    buffer.append(lines[line_idx].strip())
                line_idx += 1

        if current_section and buffer:
            text_chunk = " ".join(buffer).strip()
            if text_chunk:
                chunks.append({"page": page_num+1, "section": current_section, "text": text_chunk})

        if pending_sections:
            for missing_section in pending_sections:
                print(f"[WARNING] Section '{missing_section}' expected on page {page_num+1} but not found.")
                if buffer:
                    text_chunk = " ".join(buffer).strip()
                    if text_chunk:
                        chunks.append({"page": page_num+1, "section": missing_section, "text": text_chunk})
                        buffer = []

    # Save text
    output_file = output_dir / "raw_text.jsonl"
    with open(output_file, "w", encoding="utf-8") as f:
        for chunk in chunks:
            f.write(json.dumps(chunk, ensure_ascii=False) + "\n")

    print(f"✓ Extracted {len(chunks)} text chunks")
    print(f"✓ Clean text saved to {output_file}")

    # --- Extract tables using Camelot/pdfplumber ---
    tables_info = extract_tables(pdf_path, output_dir)

    return chunks, toc_df, tables_info

In [160]:
pdf_path = "data/sustainable-health-from-food_web.pdf"
chunks, toc_df, tables = extract_pdf_with_structure(pdf_path)

[WARNING] Section 'Appendix 8. Recommended intakes of fat, carbohydrates and protein for adults and children over 2 years (without alcohol and with fibre taken into account)' expected on page 102 but not found.
✓ Extracted 134 text chunks
✓ Clean text saved to data/raw_text.jsonl

/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (0, 0, 498.898, 708.661)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 137.1649, 437.67889999999966, 681.5164555555556)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (92.0472, 302.90479999999997, 462.89330000000035, 684.5557947368421)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 76.3326, 437.41122, 689.9815883720928)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 69.4349, 437.40632000000005, 690.1235909090908)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999999, 331.4017, 435.2284160000003, 644.9861965517242)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 110.1649, 437.70725000000033, 668.180519047619)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 191.1649, 437.6222000000001, 641.9536615384616)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 110.1648, 437.67574999999965, 688.5401)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 56.1649, 437.61484999999965, 491.49501935483875)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 299.16490000000005, 437.65649999999954, 687.3307185714286)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 96.6649, 437.6453000000005, 639.7663142857143)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 69.6649, 437.71669999999995, 490.9883965517242)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 231.6649, 437.6610499999998, 533.4069919666667)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 218.1649, 437.6589500000002, 688.4231941176471)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999999, 380.16490000000005, 437.67155000000014, 684.4593445454547)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 96.6649, 437.6138000000003, 429.4689000000001)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999997, 69.6649, 437.68730000000033, 340.4799052631579)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999999, 353.16490000000005, 437.6589500000003, 667.8538090909091)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 56.1649, 437.61275000000023, 430.0876027777778)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 56.1649, 437.6022499999998, 683.7433)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999997, 453.25890000000004, 437.7177500000005, 675.8093082413792)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 96.6649, 437.6831000000001, 655.6746204545454)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 56.1649, 437.6722500000006, 684.7606466666667)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 50.535399999999996, 437.73034999999993, 669.8225130434784)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999997, 483.579414, 437.31147579999987, 688.4124724137931)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999999, 490.3961, 437.29343719999997, 682.7366806666668)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 83.59103999999999, 432.7191999999998, 532.3289586666667)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 177.6649, 437.6631500000006, 634.8080448275863)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 263.0133, 437.62125, 665.6417761904762)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 55.77179000000001, 426.7119499999995, 260.7731661904762)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 76.5672, 437.64424999999954, 662.4263000000001)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 460.1483, 428.14099999999945, 662.2536444444444)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 173.4133, 437.65999999999985, 662.8199486486486)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 468.40379, 431.76309999999995, 652.3263809090909)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999997, 409.64200000000005, 437.61635, 663.9747043478262)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 109.41329999999999, 437.64950000000056, 662.8965380952382)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 263.0133, 437.62429999999995, 664.1871529411765)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 172.7047, 437.71249999999975, 663.1759547619049)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 114.0547, 437.6536500000001, 662.4083024390245)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 439.11049, 428.8339999999993, 659.1565097560975)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (79.43309999999998, 242.126255, 425.89389, 482.57956333333334)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 61.31569999999999, 437.59395000000006, 207.68777333333333)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999999, 392.2708, 437.6211499999996, 686.456092764706)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 154.76799, 428.9436500000001, 387.9675927647059)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999999, 473.99640000000005, 437.59850000000006, 662.4092)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 185.6818, 437.7366500000002, 662.2705777777778)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 275.8133, 437.62220000000025, 663.5718806451613)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 197.596, 437.65564999999987, 661.3658857142858)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 393.08879, 423.90949999999935, 660.1308916666666)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 248.7074, 437.66735000000057, 662.7076972972973)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.70079999999997, 422.0649, 437.60645000000045, 666.3442)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 164.1649, 437.72195000000033, 688.5241736842106)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 56.1648, 437.7135500000005, 636.0725810810811)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 56.1649, 437.69045000000034, 481.93562222222226)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 218.1649, 437.6957000000002, 496.5083571428572)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 164.1649, 437.6620999999998, 668.684194117647)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 155.535, 434.4777500000004, 611.5367000000001)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 96.6649, 437.6873000000004, 638.0553363636365)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 272.16490000000005, 437.62115000000045, 668.1347571428571)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 321.01140000000004, 429.0072500000005, 657.65039)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 56.1649, 437.6473999999998, 637.0806)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 83.1648, 437.67784999999964, 680.9352380952382)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (69.3701, 388.6216, 428.8487000000004, 657.3502031578947)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 218.1649, 437.66105, 431.4997823529412)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.7008, 56.1649, 437.6697919999996, 668.7934454545455)

✓ Extracted 137 tables total to 'data/tables'

/Users/beatricezani/Desktop/Uni/NLP/pdf_to_KnowledgeGraph_LLM/.venv/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (53.76729999999999, 246.3673, 449.4282999999997, 630.1827161904762)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

## 3) NER & Keyphrase Extraction

In [161]:
!pip install spacy
!pip install transformers
!pip install keybert
!pip install scispacy
!pip install fuzzywuzzy python-Levenshtein
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in ./.venv/lib/python3.10/site-packages (3.8.7)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./.venv/lib/python3.10/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./.venv/lib/python3.10/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./.venv/lib/python3.10/site-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./.venv/lib/python3.10/site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./.venv/lib/python3.10/site-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in ./.venv/lib/python3.10/site-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./.venv/lib/python3.10/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in ./.venv/lib/python3.10/site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./.venv/lib/python3.10/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in ./.venv/lib/python3.10/site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in ./.venv/lib/python3.10/site-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./.venv/lib/python3.10/site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in ./.venv/lib/python3.10/site-packages (from spacy) (2.2.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./.venv/lib/python3.10/site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in ./.venv/lib/python3.10/site-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.10/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in ./.venv/lib/python3.10/site-packages (from spacy) (58.1.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.10/site-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in ./.venv/lib/python3.10/site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in ./.venv/lib/python3.10/site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in ./.venv/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in ./.venv/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in ./.venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in ./.venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in ./.venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in ./.venv/lib/python3.10/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in ./.venv/lib/python3.10/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.4.1)
Requirement already satisfied: wrapt in ./.venv/lib/python3.10/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (2.0.0)
Requirement already satisfied: marisa-trie>=1.1.0 in ./.venv/lib/python3.10/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.10/site-packages (from jinja2->spacy) (3.0.3)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: transformers in ./.venv/lib/python3.10/site-packages (4.57.1)
Requirement already satisfied: filelock in ./.venv/lib/python3.10/site-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in ./.venv/lib/python3.10/site-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in ./.venv/lib/python3.10/site-packages (from transformers) (2.2.6)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.10/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./.venv/lib/python3.10/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in ./.venv/lib/python3.10/site-packages (from transformers) (2025.10.23)
Requirement already satisfied: requests in ./.venv/lib/python3.10/site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.venv/lib/python3.10/site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in ./.venv/lib/python3.10/site-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in ./.venv/lib/python3.10/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in ./.venv/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./.venv/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./.venv/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.10/site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.10/site-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.10/site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.10/site-packages (from requests->transformers) (2025.10.5)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: keybert in ./.venv/lib/python3.10/site-packages (0.9.0)
Requirement already satisfied: numpy>=1.18.5 in ./.venv/lib/python3.10/site-packages (from keybert) (2.2.6)
Requirement already satisfied: rich>=10.4.0 in ./.venv/lib/python3.10/site-packages (from keybert) (14.2.0)
Requirement already satisfied: scikit-learn>=0.22.2 in ./.venv/lib/python3.10/site-packages (from keybert) (1.7.2)
Requirement already satisfied: sentence-transformers>=0.3.8 in ./.venv/lib/python3.10/site-packages (from keybert) (5.1.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.10/site-packages (from rich>=10.4.0->keybert) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.10/site-packages (from rich>=10.4.0->keybert) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert) (0.1.2)
Requirement already satisfied: scipy>=1.8.0 in ./.venv/lib/python3.10/site-packages (from scikit-learn>=0.22.2->keybert) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in ./.venv/lib/python3.10/site-packages (from scikit-learn>=0.22.2->keybert) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./.venv/lib/python3.10/site-packages (from scikit-learn>=0.22.2->keybert) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in ./.venv/lib/python3.10/site-packages (from sentence-transformers>=0.3.8->keybert) (4.57.1)
Requirement already satisfied: tqdm in ./.venv/lib/python3.10/site-packages (from sentence-transformers>=0.3.8->keybert) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in ./.venv/lib/python3.10/site-packages (from sentence-transformers>=0.3.8->keybert) (2.9.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in ./.venv/lib/python3.10/site-packages (from sentence-transformers>=0.3.8->keybert) (0.36.0)
Requirement already satisfied: Pillow in ./.venv/lib/python3.10/site-packages (from sentence-transformers>=0.3.8->keybert) (12.0.0)
Requirement already satisfied: typing_extensions>=4.5.0 in ./.venv/lib/python3.10/site-packages (from sentence-transformers>=0.3.8->keybert) (4.15.0)
Requirement already satisfied: filelock in ./.venv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (3.20.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./.venv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in ./.venv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2025.10.23)
Requirement already satisfied: requests in ./.venv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.venv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in ./.venv/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in ./.venv/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./.venv/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (1.2.0)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./.venv/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.4.2)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.10/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.10/site-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.10/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.10/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.10/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.10/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2025.10.5)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Collecting scispacy
  Using cached scispacy-0.6.2-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: spacy<3.9.0,>=3.7.0 in ./.venv/lib/python3.10/site-packages (from scispacy) (3.8.7)
Requirement already satisfied: scipy in ./.venv/lib/python3.10/site-packages (from scispacy) (1.15.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in ./.venv/lib/python3.10/site-packages (from scispacy) (2.32.5)
Collecting conllu (from scispacy)
  Using cached conllu-6.0.0-py3-none-any.whl.metadata (21 kB)
Collecting numpy<2.0 (from scispacy)
  Using cached numpy-1.26.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (61 kB)
Requirement already satisfied: joblib in ./.venv/lib/python3.10/site-packages (from scispacy) (1.5.2)
Collecting nmslib-metabrainz==2.1.3 (from scispacy)
  Using cached nmslib-metabrainz-2.1.3.tar.gz (196 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scikit-learn>=0.20.3 in ./.venv/lib/python3.10/site-packages (from scispacy) (1.7.2)
Collecting pysbd (from scispacy)
  Using cached pysbd-0.3.4-py3-none-any.whl.metadata (6.1 kB)
Collecting pybind11>=2.2.3 (from nmslib-metabrainz==2.1.3->scispacy)
  Using cached pybind11-3.0.1-py3-none-any.whl.metadata (10.0 kB)
Requirement already satisfied: psutil in ./.venv/lib/python3.10/site-packages (from nmslib-metabrainz==2.1.3->scispacy) (7.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.0.0->scispacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.0.0->scispacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.0.0->scispacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.0.0->scispacy) (2025.10.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (4.67.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.12.3)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.1.6)
Requirement already satisfied: setuptools in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (58.1.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in ./.venv/lib/python3.10/site-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in ./.venv/lib/python3.10/site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.9.0,>=3.7.0->scispacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.9.0,>=3.7.0->scispacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.9.0,>=3.7.0->scispacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.9.0,>=3.7.0->scispacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.9.0,>=3.7.0->scispacy) (0.4.2)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in ./.venv/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy<3.9.0,>=3.7.0->scispacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in ./.venv/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy<3.9.0,>=3.7.0->scispacy) (0.1.5)
INFO: pip is looking at multiple versions of thinc to determine which version is compatible with other requirements. This could take a while.
Collecting thinc<8.4.0,>=8.3.4 (from spacy<3.9.0,>=3.7.0->scispacy)
  Using cached thinc-8.3.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (15 kB)
Collecting blis<1.3.0,>=1.2.0 (from thinc<8.4.0,>=8.3.4->spacy<3.9.0,>=3.7.0->scispacy)
  Using cached blis-1.2.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (7.4 kB)
Requirement already satisfied: click>=8.0.0 in ./.venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in ./.venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in ./.venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (14.2.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in ./.venv/lib/python3.10/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.9.0,>=3.7.0->scispacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in ./.venv/lib/python3.10/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.9.0,>=3.7.0->scispacy) (7.4.1)

In [162]:
import json
import pandas as pd
import spacy
from keybert import KeyBERT
import yaml

# load Text Chunks
with open('data/raw_text.jsonl', 'r') as f:
    text_chunks = [json.loads(line) for line in f]
df_chunks = pd.DataFrame(text_chunks)
print(f"Loaded {len(df_chunks)} text chunks.")

# Load Ontology
with open('data/ontology.yaml', 'r') as f:
    ontology = yaml.safe_load(f)
entity_classes = list(ontology.get('classes', {}).keys())
print(f"Ontology classes: {entity_classes}")

Loaded 134 text chunks.
Ontology classes: ['ingredient', 'nutrient', 'technique', 'dietaryGuideline', 'healthOutcome', 'environmentImpact']

In [163]:
!pip install yake

Requirement already satisfied: yake in ./.venv/lib/python3.10/site-packages (0.6.0)
Requirement already satisfied: click>=6.0 in ./.venv/lib/python3.10/site-packages (from yake) (8.3.0)
Requirement already satisfied: jellyfish in ./.venv/lib/python3.10/site-packages (from yake) (1.2.1)
Requirement already satisfied: networkx in ./.venv/lib/python3.10/site-packages (from yake) (3.4.2)
Requirement already satisfied: numpy>=1.23.5 in ./.venv/lib/python3.10/site-packages (from yake) (2.2.6)
Requirement already satisfied: segtok in ./.venv/lib/python3.10/site-packages (from yake) (1.5.11)
Requirement already satisfied: tabulate in ./.venv/lib/python3.10/site-packages (from yake) (0.9.0)
Requirement already satisfied: regex in ./.venv/lib/python3.10/site-packages (from segtok->yake) (2025.10.23)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

## 4. Relation Extraction & Triple Building
- Use rule-based patterns and/or relation extraction models to detect relations (e.g., Ingredient X contains
Nutrient Y, Technique Z requires Temperature T).
- Convert to triples (RDF or property graph). Include provenance (page, line span).
- Deduplicate and validate (schema consistency).
- Deliverables: triples.ttl (RDF) or graph.json (property graph).

In [164]:
import json
from rdflib import Graph, Namespace, URIRef, Literal
from collections import defaultdict

# Load ontology namespace
EX = Namespace("http://example.org/food#")

# Initialize RDF graph
g = Graph()
g.bind("ex", EX)

# Load entities
entities = []
with open("data/entities_lowercased.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        entities.append(json.loads(line))

# Flatten mentions: one record per page + entity
flat_entities = []
for e in entities:
    for mention in e.get("mentions", []):
        flat_entities.append({
            "id": e["id"],
            "entity": e["label"],
            "ontology_type": e["type"],
            "page": mention["page"],
            "surface": mention["surface"],
            "context": mention.get("context", "")
        })

# Simple canonicalization: lowercasing and deduplicating by page & type
canonical_entities = {}
for e in flat_entities:
    key = (e["page"], e["ontology_type"], e["entity"].lower())
    canonical_entities[key] = e

# Group entities by page
entities_by_page = defaultdict(list)
for (page, otype, _), e in canonical_entities.items():
    entities_by_page[page].append(e)

# Relation extraction rules (simple co-occurrence + keyword heuristics)
def extract_relations(page_entities):
    triples = []
    for e1 in page_entities:
        for e2 in page_entities:
            if e1 == e2:
                continue
            # Ingredient → Nutrient
            if e1["ontology_type"] == "ingredient" and e2["ontology_type"] == "nutrient":
                triples.append((e1["entity"], "hasNutrient", e2["entity"]))

            # Ingredient → Technique
            elif e1["ontology_type"] == "ingredient" and e2["ontology_type"] == "technique":
                triples.append((e1["entity"], "usesTechnique", e2["entity"]))

            # Ingredient → DietaryGuideline
            elif e1["ontology_type"] == "ingredient" and e2["ontology_type"] == "dietaryGuideline":
                triples.append((e1["entity"], "hasGuideline", e2["entity"]))

            # Ingredient → HealthOutcome
            elif e1["ontology_type"] == "ingredient" and e2["ontology_type"] == "healthOutcome":
                triples.append((e1["entity"], "associatedWithOutcome", e2["entity"]))

            # Ingredient → EnvironmentImpact
            elif e1["ontology_type"] == "ingredient" and e2["ontology_type"] == "environmentImpact":
                triples.append((e1["entity"], "hasEnvironmentalImpact", e2["entity"]))

            # Nutrient → HealthOutcome
            elif e1["ontology_type"] == "nutrient" and e2["ontology_type"] == "healthOutcome":
                triples.append((e1["entity"], "affectsRiskOf", e2["entity"]))

            # DietaryGuideline → Technique
            elif e1["ontology_type"] == "dietaryGuideline" and e2["ontology_type"] == "technique":
                triples.append((e1["entity"], "recommendsTechnique", e2["entity"]))

            # DietaryGuideline → HealthOutcome
            elif e1["ontology_type"] == "dietaryGuideline" and e2["ontology_type"] == "healthOutcome":
                triples.append((e1["entity"], "aimsToImprove", e2["entity"]))

            # DietaryGuideline → EnvironmentImpact
            elif e1["ontology_type"] == "dietaryGuideline" and e2["ontology_type"] == "environmentImpact":
                triples.append((e1["entity"], "guidelineTargetsImpact", e2["entity"]))

            # Technique → EnvironmentImpact
            elif e1["ontology_type"] == "technique" and e2["ontology_type"] == "environmentImpact":
                triples.append((e1["entity"], "affectsImpactCategory", e2["entity"]))
    return triples

# Build RDF triples
for page, page_entities in entities_by_page.items():
    relations = extract_relations(page_entities)
    for subj, pred, obj in relations:
        subj_uri = EX[subj.replace(" ", "_")]
        obj_uri = EX[obj.replace(" ", "_")]
        g.add((subj_uri, EX[pred], obj_uri))
        # store page info as triple-level metadata (comment)
        g.add((subj_uri, RDFS.comment, Literal(f"Found on page {page}")))


# Serialize graph to Turtle
g.serialize("data/triples1.ttl", format="turtle")
print("RDF triples saved to triples.ttl")

RDF triples saved to triples.ttl

## point 5

In [165]:
!pip install rdflib pandas

Requirement already satisfied: rdflib in ./.venv/lib/python3.10/site-packages (7.3.0)
Requirement already satisfied: pandas in ./.venv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: isodate<1.0.0,>=0.7.2 in ./.venv/lib/python3.10/site-packages (from rdflib) (0.7.2)
Requirement already satisfied: pyparsing<4,>=2.1.0 in ./.venv/lib/python3.10/site-packages (from rdflib) (3.2.5)
Requirement already satisfied: numpy>=1.22.4 in ./.venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [166]:
from rdflib import Graph, Namespace, URIRef, Literal
from rdflib.namespace import RDF, RDFS
import pandas as pd

# Load your triples.ttl file
g = Graph()
g.parse("data/triples1.ttl", format="turtle")

print(f"Loaded {len(g)} triples")

Loaded 4796 triples

In [167]:
EX = Namespace("http://example.org/ex#")
g.bind("ex", EX)

In [168]:
# Example SPARQL query: Count total triples

q1 = """SELECT (COUNT(*) AS ?totalTriples) WHERE { ?s ?p ?o . }"""
for row in g.query(q1):
    print("Total Triples:", row.totalTriples)

Total Triples: 4796

In [169]:
# Example SPARQL query: List all entities and their types

q2 = """
SELECT ?entity ?nutrient
WHERE {
  ?entity ex:hasNutrient ?nutrient .
}
LIMIT 20
"""
pd.DataFrame(g.query(q2), columns=["Entity", "Nutrient"])

                                    Entity                         Nutrient
0          http://example.org/food#alcohol  http://example.org/food#calcium
1           http://example.org/food#barley  http://example.org/food#calcium
2          http://example.org/food#berries  http://example.org/food#calcium
3        http://example.org/food#beverages  http://example.org/food#calcium
4          http://example.org/food#cereals  http://example.org/food#calcium
5            http://example.org/food#dairy  http://example.org/food#calcium
6             http://example.org/food#eggs  http://example.org/food#calcium
7             http://example.org/food#fats  http://example.org/food#calcium
8             http://example.org/food#fish  http://example.org/food#calcium
9           http://example.org/food#fruits  http://example.org/food#calcium
10          http://example.org/food#grains  http://example.org/food#calcium
11         http://example.org/food#legumes  http://example.org/food#calcium
12            http://example.org/food#milk  http://example.org/food#calcium
13            http://example.org/food#nuts  http://example.org/food#calcium
14            http://example.org/food#oats  http://example.org/food#calcium
15            http://example.org/food#oils  http://example.org/food#calcium
16        http://example.org/food#potatoes  http://example.org/food#calcium
17         http://example.org/food#poultry  http://example.org/food#calcium
18  http://example.org/food#processed_meat  http://example.org/food#calcium
19        http://example.org/food#red_meat  http://example.org/food#calcium

In [170]:
q3 = """
SELECT ?entity ?comment
WHERE {
  ?entity rdfs:comment ?comment .
}
ORDER BY ?comment
LIMIT 5
"""

results = g.query(q3)
df = pd.DataFrame(results, columns=["Entity", "Comment"])

# Optionally extract numeric page number from the comment text
df["Page"] = df["Comment"].str.extract(r"(\d+)")
df.drop(columns=["Comment"], inplace=True)
df

                                   Entity Page
0         http://example.org/food#poultry   10
1  http://example.org/food#processed_meat   10
2        http://example.org/food#red_meat   10
3         http://example.org/food#alcohol  102
4         http://example.org/food#berries  102

## Point 6

In [171]:
from rdflib import Graph, Namespace, Literal
import pandas as pd, json

g = Graph()
g.parse("data/triples1.ttl", format="turtle")
EX = Namespace("http://example.org/ex#")
g.bind("ex", EX)
print(f"Loaded {len(g)} triples")

Loaded 4796 triples

In [172]:
print("Sample predicates from your TTL:")
for p in set(g.predicates()):
    print(p)

Sample predicates from your TTL:
http://example.org/food#hasGuideline
http://example.org/food#aimsToImprove
http://example.org/food#usesTechnique
http://example.org/food#affectsRiskOf
http://www.w3.org/2000/01/rdf-schema#comment
http://example.org/food#affectsImpactCategory
http://example.org/food#associatedWithOutcome
http://example.org/food#recommendsTechnique
http://example.org/food#guidelineTargetsImpact
http://example.org/food#hasNutrient
http://example.org/food#hasEnvironmentalImpact

In [173]:
query = """
SELECT ?s ?p ?o ?page
WHERE {
  ?s ?p ?o .
  OPTIONAL { ?s ex:page ?page . }
  FILTER(STRSTARTS(STR(?p), "http://example.org/food#"))
}
"""

rows = []
for s, p, o, page in g.query(query):
    rows.append({
        "subject": str(s).split("#")[-1],
        "predicate": str(p).split("#")[-1],
        "object": str(o).split("#")[-1],
        "page": str(page) if page else None
    })

facts_df = pd.DataFrame(rows)
facts_df.head()

              subject               predicate          object  page
0  include_osteopenia  guidelineTargetsImpact        land_use  None
1      processed_meat            hasGuideline   include_whole  None
2             berries             hasNutrient         protein  None
3           beverages   associatedWithOutcome  blood_pressure  None
4          vegetables             hasNutrient           fibre  None

In [174]:

def make_paraphrases(row):
    s, p, o = row["subject"], row["predicate"], row["object"]

    templates = {
        "hasNutrient": [
            f"{s} contains {o}.",
            f"{o} is a nutrient found in {s}."
        ],
        "usesTechnique": [
            f"{s} is prepared using {o}.",
            f"The preparation of {s} involves {o}."
        ],
        "hasGuideline": [
            f"{s} follows the guideline: {o}.",
            f"The dietary guideline {o} applies to {s}."
        ],
        "recommendsTechnique": [
            f"The guideline {s} recommends {o}.",
            f"{s} suggests using the technique {o}."
        ],
        "aimsToImprove": [
            f"The guideline {s} aims to improve {o}.",
            f"{s} targets the health outcome {o}."
        ],
        "affectsRiskOf": [
            f"{s} affects the risk of {o}.",
            f"Consuming {s} is associated with risk of {o}."
        ],
        "associatedWithOutcome": [
            f"{s} is associated with the health outcome {o}.",
            f"{s} has a relationship with {o}."
        ],
        "hasEnvironmentalImpact": [
            f"{s} has an environmental impact: {o}.",
            f"{s} contributes to {o} impact."
        ],
        "guidelineTargetsImpact": [
            f"The guideline {s} targets environmental impact {o}.",
            f"{s} aims to reduce or manage {o}."
        ],
        "affectsImpactCategory": [
            f"{s} affects the environmental impact category {o}.",
            f"The technique {s} tends to influence {o}."
        ],
    }

    # Fallback for predicates not listed
    result = templates.get(p, [f"{s} {p} {o}."])
    return result if isinstance(result, list) else [str(result)]


# Optional: print first few paraphrases for inspection
for i, row in facts_df.head(3).iterrows():
    print(make_paraphrases(row))


# Apply the paraphrase function
facts_df["paraphrases"] = facts_df.apply(lambda row: make_paraphrases(row), axis=1).astype(object)

# Save facts with paraphrases to JSONL
facts_jsonl_path = "data/facts.jsonl"
with open(facts_jsonl_path, "w", encoding="utf-8") as f:
    for _, row in facts_df.iterrows():
        record = {
            "subject": row["subject"],
            "predicate": row["predicate"],
            "object": row["object"],
            "page": row["page"],
            "paraphrases": row["paraphrases"]
        }
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

print(f"Facts with paraphrases saved to {facts_jsonl_path}")

['The guideline include_osteopenia targets environmental impact land_use.', 'include_osteopenia aims to reduce or manage land_use.']
['processed_meat follows the guideline: include_whole.', 'The dietary guideline include_whole applies to processed_meat.']
['berries contains protein.', 'protein is a nutrient found in berries.']
Facts with paraphrases saved to data/facts.jsonl

## Point 7

In [175]:
facts = []
with open("data/facts.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        facts.append(json.loads(line))

facts_df = pd.DataFrame(facts)

In [176]:
# return top-k facts supporting a query
def get_grounding(subject=None, predicate=None, object_=None, top_k=3):
    df = facts_df.copy()
    if subject: df = df[df['subject'].str.contains(subject, case=False)]
    if predicate: df = df[df['predicate'].str.contains(predicate, case=False)]
    if object_: df = df[df['object'].str.contains(object_, case=False)]
    df = df.head(top_k)
    return df[['subject','predicate','object','page']].to_dict(orient='records')

In [177]:
def generate_response(instruction_type, **kwargs):
    """
    Returns a text response and grounding facts based on instruction type.
    """
    if instruction_type == "factoid":
        # kwargs: subject, predicate
        # example: subject="Spinach", predicate="hasNutrient"
        grounding = get_grounding(subject=kwargs.get("subject"), predicate=kwargs.get("predicate"), top_k=3)
        if grounding:
            objects = [g['object'] for g in grounding]
            pages = [str(g['page']) for g in grounding if g['page']]
            answer = f"{', '.join(objects)} (Source: p.{', p.'.join(pages)})"
        else:
            answer = "No data found."
            grounding = []
        return answer, grounding

    elif instruction_type == "list":
        # kwargs: predicate, object (filter)
        grounding = get_grounding(predicate=kwargs.get("predicate"), object_=kwargs.get("object_"), top_k=5)
        if grounding:
            objects = [g['subject'] for g in grounding]
            pages = [str(g['page']) for g in grounding if g['page']]
            answer = f"{', '.join(objects)}. (Source: p.{', p.'.join(pages)})"
        else:
            answer = "No data found."
            grounding = []
        return answer, grounding

    # reasoning/constraint can be implemented similarly by filtering on multiple columns

In [178]:
dataset = []

# Example Factoid QA
instruction = "What nutrient is high in eggs?"
output, grounding = generate_response("factoid", subject="eggs", predicate="hasNutrient")
dataset.append({
    "instruction": instruction,
    "input": "",
    "output": output,
    "grounding": grounding
})

# Example List / Compare
instruction2 = "List two ingredients rich in fiber."
output2, grounding2 = generate_response("list", predicate="hasNutrient", object_="fiber")
dataset.append({
    "instruction": instruction2,
    "input": "",
    "output": output2,
    "grounding": grounding2
})

# Save to JSONL
with open("data/instruction_response_dataset.jsonl", "w", encoding="utf-8") as f:
    for item in dataset:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")

print(f"Generated {len(dataset)} instruction-response pairs")

Generated 2 instruction-response pairs

In [179]:
# Generate diverse QA pairs from facts

import json
import random
import pandas as pd
from pathlib import Path

# establish paths
facts_path = Path("data/facts.jsonl")
output_dir = Path("data/train/test/val")
output_dir.mkdir(parents=True, exist_ok=True)

# laad facts
facts = []
with open(facts_path, "r", encoding="utf-8") as f:
    for line in f:
        facts.append(json.loads(line))
facts_df = pd.DataFrame(facts)

print(f"Loaded {len(facts_df)} facts from {facts_path}")


def get_page_ref(pages):
    if not pages:
        return ""
    pages = [str(p) for p in pages if p]
    return f"(Source: p.{', p.'.join(pages)})" if pages else ""

def get_grounding(subset):
    grounding = []
    for _, row in subset.iterrows():
        grounding.append({
            "s": row["subject"],
            "p": row["predicate"],
            "o": row["object"],
            "page": row["page"]
        })
    return grounding


# define templates for different types of questions
TEMPLATES = {
    "hasNutrient": {
        "factoid": [
            "What nutrient is found in {s}?",
            "Which nutrient does {s} provide?",
            "What is the main nutrient in {s}?",
            "What does {s} contain that supports health?",
            "{s} is rich in which nutrient?"
        ],
        "list": [
            "List foods rich in {o}.",
            "Which ingredients are good sources of {o}?",
            "Give examples of foods containing {o}.",
            "Name three foods that are high in {o}."
        ],
        "constraint": [
            "Give two ingredients that contain {o}.",
            "Find vegan foods rich in {o}.",
            "List foods with high {o} content under 200 kcal per 100g."
        ]
    },
    "associatedWithOutcome": {
        "factoid": [
            "What health outcome is {s} associated with?",
            "How does consuming {s} affect health?",
            "{s} is linked to which health condition?",
            "What condition may be influenced by {s}?"
        ],
        "list": [
            "List foods associated with reduced risk of {o}.",
            "Which foods promote {o}?",
            "Name foods linked to {o}."
        ]
    },
    "affectsRiskOf": {
        "factoid": [
            "What health outcome does {s} influence?",
            "Which disease risk is affected by {s}?",
            "How does {s} affect the risk of {o}?",
            "What role does {s} play in preventing {o}?"
        ]
    },
    "usesTechnique": {
        "factoid": [
            "What technique is used to prepare {s}?",
            "How is {s} typically cooked or processed?",
            "What preparation method applies to {s}?"
        ]
    },
    "affectsImpactCategory": {
        "factoid": [
            "What environmental impact is influenced by {s}?",
            "Which sustainability impact is affected by {s}?",
            "How does {s} affect environmental footprint?"
        ],
        "reasoning": [
            "If a recipe uses {s}, what environmental impact may increase?",
            "When {s} is used, which environmental category might be affected?"
        ]
    },
    "hasGuideline": {
        "factoid": [
            "What dietary guideline applies to {s}?",
            "What recommendation is given regarding {s}?",
            "What official advice mentions {s}?"
        ]
    },
    "aimsToImprove": {
        "factoid": [
            "What health outcome does {s} aim to improve?",
            "What benefit does {s} target?",
            "Which condition is addressed by {s}?"
        ]
    },
    "guidelineTargetsImpact": {
        "factoid": [
            "What environmental impact does {s} aim to reduce?",
            "Which sustainability metric is targeted by {s}?"
        ]
    }
}



# generate functions of different type
def generate_factoid_qa(fact):
    # TYPE 1: Factoid-style questions
    s, p, o, page = fact["subject"], fact["predicate"], fact["object"], fact["page"]

    templates = TEMPLATES.get(p, {}).get("factoid", [])
    if not templates:
        instruction = f"What is the relationship between {s.replace('_', ' ')} and {o.replace('_', ' ')}?"
        output = f"{s.replace('_', ' ')} {p.replace('_', ' ')} {o.replace('_', ' ')}. {get_page_ref([page])}"
    else:
        instruction = random.choice(templates).format(s=s.replace("_", " "), o=o.replace("_", " "))
        output = f"{s.replace('_', ' ')} {p.replace('_', ' ')} {o.replace('_', ' ')}. {get_page_ref([page])}"

    grounding = [fact.to_dict()]
    return {"instruction": instruction.strip(), "input": "", "output": output.strip(), "grounding": grounding}


def generate_list_compare(df):
    # TYPE 2: List/Compare-style questions
    nutrient_rows = df[df["predicate"] == "hasNutrient"]
    if len(nutrient_rows) < 3:
        return None

    nutrient = random.choice(nutrient_rows["object"].unique().tolist())
    subset = nutrient_rows[nutrient_rows["object"] == nutrient].sample(min(4, len(nutrient_rows)))
    ingredients = [s.replace('_', ' ') for s in subset["subject"].tolist()]
    pages = subset["page"].tolist()

    templates = TEMPLATES["hasNutrient"]["list"]
    instruction = random.choice(templates).format(o=nutrient.replace("_", " "))
    output = "; ".join(ingredients) + f". {get_page_ref(pages)}"
    grounding = get_grounding(subset)
    return {"instruction": instruction.strip(), "input": "", "output": output.strip(), "grounding": grounding}


def generate_reasoning(df):
    # TYPE 3: Reasoning-style questions
    tech_rows = df[df["predicate"] == "affectsImpactCategory"]
    if len(tech_rows) == 0:
        return None

    row = tech_rows.sample(1).iloc[0]
    s, o, page = row["subject"], row["object"], row["page"]
    templates = TEMPLATES["affectsImpactCategory"]["reasoning"]
    instruction = random.choice(templates).format(s=s.replace("_", " "), o=o.replace("_", " "))
    output = f"{s.replace('_', ' ')} affects {o.replace('_', ' ')} impact. {get_page_ref([page])}"
    grounding = [row.to_dict()]
    return {"instruction": instruction.strip(), "input": "", "output": output.strip(), "grounding": grounding}


def generate_constraint_query(df):
    # TYPE 4: Constraint-style questions
    nutrient_rows = df[df["predicate"] == "hasNutrient"]
    if len(nutrient_rows) == 0:
        return None

    nutrient = random.choice(nutrient_rows["object"].unique().tolist())
    subset = nutrient_rows[nutrient_rows["object"] == nutrient].sample(min(3, len(nutrient_rows)))
    ingredients = [s.replace('_', ' ') for s in subset["subject"].tolist()]
    pages = subset["page"].tolist()

    templates = TEMPLATES["hasNutrient"]["constraint"]
    instruction = random.choice(templates).format(o=nutrient.replace("_", " "))
    output = "; ".join(ingredients) + f". {get_page_ref(pages)}"
    grounding = get_grounding(subset)
    return {"instruction": instruction.strip(), "input": "", "output": output.strip(), "grounding": grounding}


# create the dataset
dataset = []

# one QA per fact
for _, fact in facts_df.iterrows():
    dataset.append(generate_factoid_qa(fact))

# extra random examples
for _ in range(40):
    q = generate_list_compare(facts_df)
    if q: dataset.append(q)

for _ in range(20):
    q = generate_reasoning(facts_df)
    if q: dataset.append(q)

for _ in range(20):
    q = generate_constraint_query(facts_df)
    if q: dataset.append(q)

dataset = [d for d in dataset if d]
print(f"Generated {len(dataset)} instruction–response pairs.")

# split in train, test and validation
# after shuffling 80% train, 10% val, 10% test
random.shuffle(dataset)
n = len(dataset)
train_end = int(0.8 * n)
val_end = int(0.9 * n)

splits = {
    "train": dataset[:train_end],
    "val": dataset[train_end:val_end],
    "test": dataset[val_end:]
}

for split_name, data in splits.items():
    out_path = output_dir / f"{split_name}_instructions.jsonl"
    with open(out_path, "w", encoding="utf-8") as f:
        for record in data:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    print(f"Saved {len(data)} {split_name} examples → {out_path}")

Loaded 4218 facts from data/facts.jsonl
Generated 4298 instruction–response pairs.
Saved 3438 train examples → data/train/test/val/train_instructions.jsonl
Saved 430 val examples → data/train/test/val/val_instructions.jsonl
Saved 430 test examples → data/train/test/val/test_instructions.jsonl

## Point 7

In [180]:
# comparing two ways of answering questions using your knowledge graph (KG) and/or an LLM

# idea:
# Zero-shot: “I’m asking GPT what it remembers about nutrition from training data.”
# RAG-KG: “I’m giving GPT the verified facts from the PDF and asking it to answer based only on that.”